pom.xml
src/main/java/no/ssb/dlp/pseudo/service/export/ExportController.java
src/main/java/no/ssb/dlp/pseudo/service/export/ExportService.java
src/main/resources/logback.xml

The fix is to use the latest version of dapla-dlp-pseudo-core which uses
a different strategy when zipping the export files.
Also, exporting is now done in separate threads, and the target export paths
are returned upfront.

Fix OOM excepton when exporting large datasets

---

doc/requests/examples.http
pom.xml
src/main/java/no/ssb/dlp/pseudo/service/keys/KeyController.java
src/main/java/no/ssb/dlp/pseudo/service/keys/KeyService.java
src/main/java/no/ssb/dlp/pseudo/service/pseudo/PseudoController.java
src/main/java/no/ssb/dlp/pseudo/service/tink/KmsConfig.java
src/test/resources/application-test.yml

This PR adds a `/keys` REST endpoint, that provides functionality for creating new Data Encryption Keys, wrapped by a user specified Key Encryption Key (KEK).
It is possible to use the generated DEK as a custom key for pseudonymization.
If a kek is not specified, then the default KEK is used.
Example payload:
```json
{
"kekUri": "gcp-kms://projects/some-project/locations/europe-north1/keyRings/some-keyring/cryptoKeys/some-kek-1",
"encryptedKeyset": "CjQAp9...OQ=",
"keysetInfo": {
"primaryKeyId": 123456789,
"keyInfo": [
{
"typeUrl": "type.googleapis.com/google.crypto.tink.AesSivKey",
"status": "ENABLED",
"keyId": 123456789,
"outputPrefixType": "TINK"
}
]
}
}
```

Support data encryption key generation

---

cloudbuild.yml

This PR is part of adding a Cloud Build trigger for dapla-dlp-pseudo-service. See https://github.com/statisticsnorway/dapla-felles-iac/pull/43

Add build file for Cloud Run

---

Dockerfile
Makefile
conf/application.yml
conf/bootstrap.yml

This enables environment specific differences to be more easily overridden by environment variables. Cloud Run cannot set up configuration files as volume mounts, and therefore needs to configure the service via environment variables.

Add default configurations

---

src/main/java/no/ssb/dlp/pseudo/service/pseudo/PseudoController.java

Removed principal argument from pseudonymizeFile. User principal will no longer be logged.

Remove principal from pseudonymize/file endpoint

---

src/main/java/no/ssb/dlp/pseudo/service/security/CloudRunEndpointFilter.java

Added a filter for incoming HTTP requests that restricts access to all endpoints except /pseudonymize/file when then configuration property "endpoints.cloud-run.enabled" is set to true.
Ref: https://statistics-norway.atlassian.net/jira/software/projects/STAT/boards/150/backlog?selectedIssue=STAT-407

Add HTTP filter for Cloud Run deployment

---

conf/application-local.yml
conf/application-sid-client.yml
src/main/java/no/ssb/dlp/pseudo/service/security/CustomRolesFinder.java

When the pseudo-service application is deployed to Cloud Run, this will make it easier to configure the SID-service endpoint by simply overriding the URL and PATH variables.
The property `endpoints.cloud-run.enabled` is now also used to toggle CustomRolesFinder.

Extract sid-client configuration to separate config.

---

src/main/java/no/ssb/dlp/pseudo/service/pseudo/RecordMapProcessorFactory.java

Initialize `FieldPseudonymizer` outside of lambda expression.. This substantially improves performace since the `initPseudoFuncConfigs` was called for every apply.

Improved performance in FieldPseudonymizer

---

src/main/java/no/ssb/dlp/pseudo/service/sid/IdTokenFilter.java

The IdTokenFilter is used only for service-to-service authentication between Cloud Run services. Services in k8s use istio-proxy, so we disable IdTokenFilter in k8s environment.

Disable IdTokenFilter in k8s environment

---

conf/application-local.yml
doc/requests/examples-sid.http
pom.xml
src/main/java/no/ssb/dlp/pseudo/service/sid/ExternalSidService.java
src/main/java/no/ssb/dlp/pseudo/service/sid/LocalSidService.java
src/main/java/no/ssb/dlp/pseudo/service/sid/SidClient.java
src/main/java/no/ssb/dlp/pseudo/service/sid/SidMapper.java
src/main/java/no/ssb/dlp/pseudo/service/sid/SidService.java
src/main/java/no/ssb/dlp/pseudo/service/sid/VersionInfo.java
src/test/java/no/ssb/dlp/pseudo/service/sid/SidMapperTest.java

Internal ticket ref: STAT-588
See also:
- https://github.com/statisticsnorway/dapla-dlp-pseudo-func/pull/10
- https://github.com/statisticsnorway/dapla-dlp-pseudo-core/pull/20

Add support for supplying a version timestamp to the 'map-sid' function

---

doc/requests/examples-sid.http
src/main/java/no/ssb/dlp/pseudo/service/pseudo/PseudoController.java
src/main/java/no/ssb/dlp/pseudo/service/sid/InvalidSidVersionException.java
src/main/java/no/ssb/dlp/pseudo/service/sid/SidMapper.java

Previously, an internal server error (code 500) was returned when an invalid SID version was encountered

Throw 400 when invalid SID version is supplied in request

---

conf/application-local.yml
conf/application-sid-client-ext.yml
doc/requests/examples-sid.http
pom.xml
src/main/java/no/ssb/dlp/pseudo/service/sid/ExternalSidService.java
src/main/java/no/ssb/dlp/pseudo/service/sid/LocalSidService.java
src/main/java/no/ssb/dlp/pseudo/service/sid/SidClient.java
src/main/java/no/ssb/dlp/pseudo/service/sid/SidMapper.java
src/main/java/no/ssb/dlp/pseudo/service/sid/SidService.java
src/main/java/no/ssb/dlp/pseudo/service/sid/SnapshotInfo.java
src/main/java/no/ssb/dlp/pseudo/service/sid/VersionInfo.java
src/test/java/no/ssb/dlp/pseudo/service/sid/SidMapperTest.java

This change adds support for specifying the version timestamp according to the new SID format (YYYY-MM-DD)

Add support for new timestamp format in SID service

---

Dockerfile

There has been exposed a vulnerability in the `glibc` package that stops the newest build from completing. The vulnerability is found in the docker image, so this is an attempt to run `dist-upgrade` with `apt` in order to update `glibc`

Upgrade Ubuntu in Dockerfile to fix vulnerability

---

conf/application-local.yml
src/main/java/no/ssb/dlp/pseudo/service/pseudo/PseudoController.java
src/main/java/no/ssb/dlp/pseudo/service/security/CustomRolesFinder.java
src/main/java/no/ssb/dlp/pseudo/service/security/PseudoServiceRole.java
src/main/java/no/ssb/dlp/pseudo/service/security/StaticRolesConfig.java

This PR adds a `user` role in addition to the `admin` role. Also use the `isAuthenticated()` keyword to add all authenticated users to a given role.
This enables access control to all the endpoints with environment specific configurations.
Internal ticket ID: DPSTAT-723

Add new user role for authenticated users.

---

doc/requests/README.md

The 'keycloak_token' field is required even when running the Pseudo Service locally, so we should include a stub in the docs/requests/README.md

Add 'keycloak_token' field in README

---

src/main/java/no/ssb/dlp/pseudo/service/pseudo/PseudoController.java
src/main/java/no/ssb/dlp/pseudo/service/pseudo/PseudoField.java
src/main/java/no/ssb/dlp/pseudo/service/pseudo/RecordMapProcessorFactory.java
src/test/java/no/ssb/dlp/pseudo/service/pseudo/DepseudoFieldTest.java
src/test/java/no/ssb/dlp/pseudo/service/pseudo/PseudoFieldTest.java
src/test/java/no/ssb/dlp/pseudo/service/pseudo/RepseudoFieldTest.java

Micronaut attemps to wrap the `HttpResponse<Publisher<String>>` into a JSON array - which is not correct. According to the docs one can avoid this by returning `HttpResponse<Flowable<byte[]>>` instead.
Also fixed missing `NULL_VALUE` metric in PseudoField and don't rely on missing `sidSnapshotDate` when setting `MISSING_SID` metric.
This fixed the internal ticket ID: DPSTAT-839

PseudoController now correctly returns a JSON object with correct content-type and encoding

---

pom.xml
src/main/java/no/ssb/dlp/pseudo/service/filters/CorrelationIdFilter.java
src/main/java/no/ssb/dlp/pseudo/service/filters/TransactionIdFilter.java
src/main/java/no/ssb/dlp/pseudo/service/pseudo/PseudoController.java
src/main/resources/logback.xml

All incoming HTTP requests now log the transactionID of the request being made.

[DPSTAT-837] Implement TransactionID logging

---

src/main/java/no/ssb/dlp/pseudo/service/filters/CorrelationIdFilter.java
src/main/java/no/ssb/dlp/pseudo/service/pseudo/PseudoController.java

- Don't parse `X-Correlation-Id` header as ULID, be less restrictive
- Add `X-Correlation-Id` header to all API responses

[DPSTAT-837] More correlation id changes

---

src/main/java/no/ssb/dlp/pseudo/service/pseudo/RecordMapProcessorFactory.java
src/main/java/no/ssb/dlp/pseudo/service/sid/Redactor.java
src/main/java/no/ssb/dlp/pseudo/service/sid/SidMapper.java
src/test/java/no/ssb/dlp/pseudo/service/sid/RedactorTest.java
src/test/java/no/ssb/dlp/pseudo/service/sid/SidMapperTest.java

- Created a Redactor class for redacting identifiers
- Also fixed missing metadata in depseudonymize.

Identifiers such as FNR or SNR should be masked in both logs and metadata

---

openapi.properties

Fixes bug where API documentation wasn't rendered because of some changed openapi properties in the new version of `micronaut-openapi`.

Fix OpenAPI docs

---

doc/requests/examples-sid.http
src/main/java/no/ssb/dlp/pseudo/service/pseudo/PseudoConfigSplitter.java
src/main/java/no/ssb/dlp/pseudo/service/pseudo/RecordMapProcessorFactory.java
src/main/java/no/ssb/dlp/pseudo/service/sid/LocalSidService.java
src/main/java/no/ssb/dlp/pseudo/service/sid/SidMapper.java
src/test/java/no/ssb/dlp/pseudo/service/sid/SidMapperTest.java
src/test/resources/data/person_3_sid_deid.json

`PseudoConfigSplitter` should now only be triggered by the function `map-sid`, and not `map-sid-ff31` or `map-sid-daead` that was added in [this PR](https://github.com/statisticsnorway/dapla-dlp-pseudo-core/pull/39). This is because `map-sid-ff31` or `map-sid-daead` performs both mapping end encryption.
The `init`-method has been changed in the underlying libraries with a `TransformDirection`.

Deprecate use of PseudoConfigSplitter. Adapt to new mapping functions

---

src/main/java/no/ssb/dlp/pseudo/service/pseudo/RecordMapProcessorFactory.java
src/main/java/no/ssb/dlp/pseudo/service/pseudo/metadata/FieldMetadata.java
src/test/java/no/ssb/dlp/pseudo/service/pseudo/DepseudoFieldTest.java
src/test/java/no/ssb/dlp/pseudo/service/pseudo/PseudoFieldTest.java
src/test/java/no/ssb/dlp/pseudo/service/pseudo/RepseudoFieldTest.java

This PR will remove some duplicate code, and also corrrects a missing encryptionKeyReference in metadata.

Add missing encryptionKeyReference to metadata. Simplify code.

---

conf/application-local.yml
src/main/java/no/ssb/dlp/pseudo/service/security/CustomRolesFinder.java
src/main/java/no/ssb/dlp/pseudo/service/security/StaticRolesConfig.java
src/test/java/no/ssb/dlp/pseudo/service/security/CustomRolesFinderTest.java

When using `isAuthenticated()` the JWT token must be signed by a trusted issuer. The property `micronaut.security.token.jwt.signatures.jwks` is used to validate JWT tokens, but this is not enough to validate trusted issuers. For example, Google IdTokens can be issued by many different services.
This PR will restrict the use of `isAuthenticated()` to only trusted issuers like Keycloak.
Internal ticket ID: DPSTAT-888

Add extra security measure for isAuthenticated()

---

pom.xml
src/main/java/no/ssb/dlp/pseudo/service/pseudo/RecordMapProcessorFactory.java
src/main/java/no/ssb/dlp/pseudo/service/sid/LocalSidService.java
src/main/java/no/ssb/dlp/pseudo/service/sid/SidMapper.java
src/test/java/no/ssb/dlp/pseudo/service/sid/SidMapperTest.java

Instead of throwing `MappingNotFoundException ` the `SidMapper` should now respect the `MapFailureStrategy` parameter for handling mapping failures.

Fix handling of new MapFailureStrategy parameter in SidMapper

---

src/main/java/no/ssb/dlp/pseudo/service/pseudo/RecordMapProcessorFactory.java

When hitting FPE limitation return either null or the original value according to the given `MapFailureStrategy`
Also fixed bug in setting `MAPPED_SID` or `MISSING_SID` metric.

Fix return value when hitting FPE limitation

---

src/main/java/no/ssb/dlp/pseudo/service/pseudo/PseudoController.java
src/main/java/no/ssb/dlp/pseudo/service/pseudo/PseudoField.java
src/test/java/no/ssb/dlp/pseudo/service/pseudo/DepseudoFieldTest.java
src/test/java/no/ssb/dlp/pseudo/service/pseudo/PseudoFieldTest.java
src/test/java/no/ssb/dlp/pseudo/service/pseudo/RepseudoFieldTest.java

In the generated datadoc the pattern was hard-coded to `**`. This can now be set as part of the request.

The pattern should be included in the payload to the pseudonymizeField endpoint.

---

doc/requests/examples-field.http
src/main/java/no/ssb/dlp/pseudo/service/pseudo/PseudoController.java
src/main/java/no/ssb/dlp/pseudo/service/pseudo/PseudoField.java

This is a "sanity check" that ensures that the pattern actually will give a match to the provided pseudo function.
Previously the pattern was hard-coded to `**`. Now it should show the actual pattern that was used to match the field.

Validate the pattern that is sendt to the pseudonymizeField endpoint.

---

src/main/java/no/ssb/dlp/pseudo/service/pseudo/RecordMapProcessorFactory.java

When the metadata processor creates datadoc elements the `dataElementPath` should not contain the array indices. For example: `bankLaanOgForsikring.konto[0].overfoertFraBarnTilForelder.barnetsPersonidentifikator` should become `bankLaanOgForsikring.konto.overfoertFraBarnTilForelder.barnetsPersonidentifikator`
This will guarantee that we only get one unique `dataElementPath` that represents all elements in the list.

Paths in datadoc should not contain the array indices.

---

src/main/java/no/ssb/dlp/pseudo/service/pseudo/PseudoField.java
src/test/java/no/ssb/dlp/pseudo/service/pseudo/PseudoFieldTest.java

Since `name` is used to contain the paths of hierarchical data, the paths can possibly contain indices. This breaks the glob validation, so we strip array indices before validating.

Regex replace name indices when validating glob

---

.nais/alerts.yaml

- Alert if there are no replicas (critical)
- Alert if there is high CPU usage (warning)
- Alert if there is high memory usage (exceeds 90% of total memory configured) (warning)
- Alert if there is detected high numbers of error in the logs of pseudo-service (critical)
- Alert if pseudo-service is restarting often within a time limit( 3 times within 15 minutes )

add alerts for pseudo-service

---

.nais/test/nais.yaml
pom.xml
src/main/java/no/ssb/dlp/pseudo/service/health/LivenessIndicator.java
src/test/java/no/ssb/dlp/pseudo/service/health/HealthTest.java

We now serve metrics and health check endpoints on port `10220`, not on the same port as regular requests, `10210`. This is to avoid requests from outside the cluster, and possibly the internet, being able to access metrics and status of the application. These endpoints need to be unauthenticated to allow for cluster services to access them
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/pseudo-service/122)

Config health checks and Prometheus in test environment

---

.nais/prod/nais.yaml

Kubernetes pods are scheduled to a node based on request, not limit, so request should be equal to the limit
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/pseudo-service/132)

Increase memory request for prod

---

.nais/prod/nais.yaml
.nais/test/nais.yaml

This should hoppefully increase the chance that a request is processed when the pod scales down. Sadly, this is not guaranteed as the max grace period in NAIS is 180 seconds (3 minutes), not the potential maximum of 10 miinutes.
https://doc.nais.io/workloads/application/reference/application-spec/?h=grace#terminationgraceperiodseconds
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/pseudo-service/135)

Increase grace period

---

pom.xml
src/main/java/no/ssb/dlp/pseudo/service/pseudo/PseudoResponseSerializer.java
src/main/java/no/ssb/dlp/pseudo/service/pseudo/RecordMapProcessorFactory.java
src/main/java/no/ssb/dlp/pseudo/service/pseudo/metadata/FieldMetadata.java
src/main/java/no/ssb/dlp/pseudo/service/pseudo/metadata/PseudoMetadataProcessor.java
src/test/java/no/ssb/dlp/pseudo/service/pseudo/DepseudoFieldTest.java
src/test/java/no/ssb/dlp/pseudo/service/pseudo/PseudoFieldTest.java
src/test/java/no/ssb/dlp/pseudo/service/pseudo/PseudoResponseSerializerTest.java
src/test/java/no/ssb/dlp/pseudo/service/pseudo/RepseudoFieldTest.java

This reverts commit dd24acddd0f06acef4a38fd251346e346abd1484.
Because of the failed deploy of `dapla-toolbelt-pseudo v3.0.0` last week in kildomaten we're now reverting this change again so that users in the test environment won't be affected. These changes were never released to the production environment.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/pseudo-service/136)

Reapply "Revert changes to pseudo metadata (#133)" (#134)

---

.nais/prod/nais.yaml
.nais/test/nais.yaml

The use of this client causes issues like this during periods of high load
https://github.com/micronaut-projects/micronaut-security/issues/1633
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/pseudo-service/146)

Disable usage of Micronaut http client

---

src/main/java/no/ssb/dlp/pseudo/service/pseudo/PseudoField.java

When adding pseudonymization rules, the `name` of the field needs to match the `pattern`. However, when sending hierarchical data, you might index an array such that the `name` becomes `person_info/fnr[0]`, but the `pattern` is `person_info/fnr`, making the name not match the pattern. We remove the indices with a regex in order to make this fit.
Ideally, we should have a longer-term solution to this, but pattern-based traversal is so ubiquotous to `pseudo-core` that, in my opinion, it is not worth changing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/pseudo-service/149)

Remove indices from 'name' for purposes of pseudo processing
