statisticsnorway/pseudo-service

conf/application-sid-client.yml, src/main/java/no/ssb/dlp/pseudo/service/sid/IdTokenFilter.java, src/main/java/no/ssb/dlp/pseudo/service/sid/IdTokenFilterMatcher.java, src/main/java/no/ssb/dlp/pseudo/service/sid/SidClient.java
The IdTokenFilter will use the pseudo service SA to authenticate to the SID service.
=> Remove token propagation and add IdTokenFilter.

src/main/java/no/ssb/dlp/pseudo/service/pseudo/RecordMapProcessorFactory.java
Same fix as #34 which will boost performance for depseudonymize and repseudonymize as well
=> Fix Initialization of FieldPseudonymizer for depseudonymize and repseudonymize

src/main/java/no/ssb/dlp/pseudo/service/sid/SidMapper.java
The SidMapper needs to block/wait for the result of a `org.reactivestreams.Publisher`, and this was implemented incorrectly.
=> Fix bug in SidMapper that didn't wait for subscription to finish.

src/main/java/no/ssb/dlp/pseudo/service/sid/SidMapper.java
Also remove Singleton annotation from SidMapper since it is a Service Provider class, not a Service.
=> Fix ClassCastException that may happen for ReadTimeoutExceptions.

conf/application-local.yml, doc/requests/examples-sid.http, src/main/java/no/ssb/dlp/pseudo/service/sid/ExternalSidService.java, src/main/java/no/ssb/dlp/pseudo/service/sid/LocalSidService.java, src/main/java/no/ssb/dlp/pseudo/service/sid/MultiSidLookupResponse.java, src/main/java/no/ssb/dlp/pseudo/service/sid/SidLookupController.java, src/main/java/no/ssb/dlp/pseudo/service/sid/SidService.java, src/test/java/no/ssb/dlp/pseudo/service/sid/SidLookupControllerTest.java
Internal ticket ID: DPSTAT-725
=> Add endpoint to check fnr for missing sid mapping

src/main/java/no/ssb/dlp/pseudo/service/pseudo/PseudoController.java, src/main/java/no/ssb/dlp/pseudo/service/pseudo/PseudoField.java, src/test/java/no/ssb/dlp/pseudo/service/pseudo/DepseudoFieldTest.java, src/test/java/no/ssb/dlp/pseudo/service/pseudo/RepseudoFieldTest.java
=> Add field-based endpoints for depseudonymization and repseudonymization

conf/application-local.yml, doc/requests/examples-sid.http, pom.xml, src/main/java/no/ssb/dlp/pseudo/service/pseudo/RecordMapProcessorFactory.java, src/main/java/no/ssb/dlp/pseudo/service/sid/ExternalSidService.java, src/main/java/no/ssb/dlp/pseudo/service/sid/LocalSidService.java, src/main/java/no/ssb/dlp/pseudo/service/sid/MultiSidRequest.java, src/main/java/no/ssb/dlp/pseudo/service/sid/SidLookupController.java, src/main/java/no/ssb/dlp/pseudo/service/sid/SidMapper.java, src/main/java/no/ssb/dlp/pseudo/service/sid/SidService.java, src/test/java/no/ssb/dlp/pseudo/service/sid/ExternalSidServiceTest.java, src/test/java/no/ssb/dlp/pseudo/service/sid/SidLookupControllerTest.java, src/test/java/no/ssb/dlp/pseudo/service/sid/SidMapperTest.java, src/test/resources/data/person_3_sid.json, src/test/resources/data/person_3_sid_deid.json
Added support to map snr to fnr for depseudonymisering process. Made changes in mapTo() to support both fnr and snr.
=> DPSTAT-814-Implementere map sid i depseudonymisering

src/main/java/no/ssb/dlp/pseudo/service/pseudo/RecordMapProcessorFactory.java, src/main/java/no/ssb/dlp/pseudo/service/sid/MultiSidResponse.java, src/test/java/no/ssb/dlp/pseudo/service/sid/ExternalSidServiceTest.java
1. Fixed bug. Added check for null object coming from sid lookup service
2. Added changes to support new map-sid in pseudo-core
=> Fixed check for null object returned from lookup service. 

doc/requests/examples-sid.http, src/main/java/no/ssb/dlp/pseudo/service/sid/SidMapper.java, src/test/java/no/ssb/dlp/pseudo/service/sid/SidMapperTest.java
Fixed exception when Fetching snr from output when lookup service return null object .
=> Fix null pointer exception

src/main/java/no/ssb/dlp/pseudo/service/pseudo/PseudoController.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-dlp-pseudo-service/116)
=> Test 'pseudonymize/field' endpoint with BLOCKING TaskExecutor

src/main/java/no/ssb/dlp/pseudo/service/accessgroups/CloudIdentityClient.java, src/main/java/no/ssb/dlp/pseudo/service/pseudo/PseudoController.java, src/main/java/no/ssb/dlp/pseudo/service/sid/LocalSidServiceController.java, src/main/java/no/ssb/dlp/pseudo/service/sid/SidClient.java, src/main/java/no/ssb/dlp/pseudo/service/sid/SidLookupController.java, src/main/java/no/ssb/dlp/pseudo/service/sid/local/SidCacheController.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/dapla-dlp-pseudo-service/117)
=> Use virtual threads for all endpoints

Makefile, README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/pseudo-service/127)
=> Tidy README. Add notes on how to release

pom.xml, src/main/java/no/ssb/dlp/pseudo/service/pseudo/PseudoResponseSerializer.java, src/main/java/no/ssb/dlp/pseudo/service/pseudo/RecordMapProcessorFactory.java, src/main/java/no/ssb/dlp/pseudo/service/pseudo/metadata/FieldMetadata.java, src/main/java/no/ssb/dlp/pseudo/service/pseudo/metadata/PseudoMetadataProcessor.java, src/test/java/no/ssb/dlp/pseudo/service/pseudo/DepseudoFieldTest.java, src/test/java/no/ssb/dlp/pseudo/service/pseudo/PseudoFieldTest.java, src/test/java/no/ssb/dlp/pseudo/service/pseudo/PseudoResponseSerializerTest.java, src/test/java/no/ssb/dlp/pseudo/service/pseudo/RepseudoFieldTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/pseudo-service/133)
=> Revert changes to pseudo metadata

pom.xml, src/main/java/no/ssb/dlp/pseudo/service/pseudo/PseudoResponseSerializer.java, src/main/java/no/ssb/dlp/pseudo/service/pseudo/RecordMapProcessorFactory.java, src/main/java/no/ssb/dlp/pseudo/service/pseudo/metadata/FieldMetadata.java, src/main/java/no/ssb/dlp/pseudo/service/pseudo/metadata/PseudoMetadataProcessor.java, src/test/java/no/ssb/dlp/pseudo/service/pseudo/DepseudoFieldTest.java, src/test/java/no/ssb/dlp/pseudo/service/pseudo/PseudoFieldTest.java, src/test/java/no/ssb/dlp/pseudo/service/pseudo/PseudoResponseSerializerTest.java, src/test/java/no/ssb/dlp/pseudo/service/pseudo/RepseudoFieldTest.java
This reverts commit 57240a868ea2a4a69f8fcfb734fd7437130b0b58.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/pseudo-service/134)
=> Revert "Revert changes to pseudo metadata (#133)"

pom.xml, src/main/java/no/ssb/dlp/pseudo/service/pseudo/PseudoResponseSerializer.java, src/main/java/no/ssb/dlp/pseudo/service/pseudo/RecordMapProcessorFactory.java, src/main/java/no/ssb/dlp/pseudo/service/pseudo/metadata/FieldMetadata.java, src/main/java/no/ssb/dlp/pseudo/service/pseudo/metadata/PseudoMetadataProcessor.java, src/test/java/no/ssb/dlp/pseudo/service/pseudo/DepseudoFieldTest.java, src/test/java/no/ssb/dlp/pseudo/service/pseudo/PseudoFieldTest.java, src/test/java/no/ssb/dlp/pseudo/service/pseudo/PseudoResponseSerializerTest.java, src/test/java/no/ssb/dlp/pseudo/service/pseudo/RepseudoFieldTest.java
This reverts commit e77d0264dd106c3a00ff3680d2710fe18e73caed.
Internal ref: https://statistics-norway.atlassian.net/browse/DPSTAT-1281
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/pseudo-service/137)
=> [DO NOT MERGE] Apply changes to pseudo metadata again

.nais/prod/nais.yaml, src/main/java/no/ssb/dlp/pseudo/service/security/CustomRolesFinder.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/pseudo-service/144)
=> Add more logging in prod

.nais/prod/nais.yaml, src/main/java/no/ssb/dlp/pseudo/service/security/CustomRolesFinder.java
Reverts statisticsnorway/pseudo-service#144
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/pseudo-service/145)
=> Revert "Add more logging in prod"

.github/workflows/build-deploy-app.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/pseudo-service/147)
=> Fix build failure when releasing new version

src/main/java/no/ssb/dlp/pseudo/service/security/CustomRolesFinder.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/pseudo-service/151)
=> Add more debug logging for email resolving

.nais/test/nais.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/pseudo-service/153)
=> Fix config

.nais/prod/nais.yaml, .nais/test/nais.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/pseudo-service/155)
=> Remove deprecated labid issuers

.nais/prod/nais.yaml, src/main/java/no/ssb/dlp/pseudo/service/security/CustomRolesFinder.java, src/main/java/no/ssb/dlp/pseudo/service/security/StaticRolesConfig.java, src/test/java/no/ssb/dlp/pseudo/service/security/CustomRolesFinderTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/statisticsnorway/pseudo-service/156)
=> Revert roles config to not being bean
